namespace Accentuate
{
    public class Accents
    {
        public string[] accents = new string[]
        {
            "JAMAICAN",
            "GEORDIE",
            "SCOUSE",
            "HOME COUNTIES",
            "PEAK DISTRICT",
            "FRENCH",
            "GERMAN",
            "CALIFORNIAN",
            "SWEDISH",
            "DUTCH",
            "SCOTTISH",
            "WELSH",
            "IRISH",
            "DALEK",
            "SOUTH AFRICAN",
            "AUSTRALIAN",
            "BRUMMIE",
            "ARNOLD SCHWARZENEGGER",
            "BRIAN COX",
            "ITALIAN",
            "SPANISH",
            "ELVIS PRESLEY",
            "RUSSIAN",
            "BANE (DARK KNIGHT RISES)",
            "DARTH VADER",
            "FORREST GUMP",
            "BATMAN",
            "NEW YORK",
            "COCKNEY",
            "WEST COUNTRY",
            "SYLVESTER STALONE",
            "SATAN",
            "GOLLUM (LORD OF THE RINGS)",
            "WICKED WITCH OF THE WEST",
            "SCOOBY DOO",
            "JOKER (DARK KNIGHT)",
            "HARRY KANE",
            "SOUTHERN",
            "DONALD TRUMP",
            "BORIS JOHNSON",
            "SAMUEL L JACKSON",
            "SNOOP DOGGY DOGG",
            "JASON STATHAM ",
            "DWAYNE THE ROCK JOHNSON",
            "CHRIS EUBANK",
            "BOSNIAN",
            "HUMPBACK WHALE"
        };
    }
}